version: '3'

services:
  beti-session:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    volumes:
      - ./src:/usr/src/beti-session/src
    command: npm run start:dev
    restart: on-failure

  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"